[build]
  command = "npm run build"
  publish = "dist"

[[forms]]
  name = "consultation"

[context.production.environment]
  NODE_ENV = "production"

# Forms are configured directly in the HTML with data-netlify attributes

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect configuration for clean URLs
[[redirects]]
  from = "/thank-you"
  to = "/thank-you/"
  status = 301